---

- name: Make sure {{ certificates_directory }} exists
  file:
    path: "{{ certificates_directory }}"
    owner: root
    group: wheel
    mode: 0755
    state: directory

- include: install_cert.yml cert="{{ item }}"
  loop: "{{ certificates }}"
